server:
  port: 8080

trading:
  log_path: "./logs/trading.log"

redis:
  addr: "redis:6379"

market:
  intervals:
    - "5m"
    - "15m"

chart:
  candles:
    limit: 500

binance:
  rate_limit:
    requests: 200
    duration: "1m"
  secrets:
    api_key: ${BINANCE_API_KEY}
    api_secret: ${BINANCE_API_SECRET}

notify:
  channels:
    futures_announcement: 1630847448
  config:
    expiration: "10m"

telegram:
  token: ${TELEGRAM_TOKEN}
